name: mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
    sdk: ^3.1.1

dependencies:
    flutter:
        sdk: flutter
    audioplayers: ^5.2.0
    http: ^1.2.0
    english_words: ^4.0.0
    provider: ^6.0.0
    socket_io_client: ^2.0.0
    mongo_dart: ^0.10.0
    camera: ^0.10.5+9
    path_provider: ^2.1.2
    path:
    image_picker: ^1.0.7
    stacked: ^3.4.2
    flutter_screenutil: ^5.9.0
    google_nav_bar: ^5.0.6
    # google_fonts: ^6.2.0
    equatable: ^2.0.5
    flutter_image_compress: ^2.1.0
    get: ^4.3.8
    bloc: ^8.1.3
    flutter_bloc: ^8.1.4
    flutter_localizations:
        sdk: flutter
    intl: any

#-------------------- ./ PACKAGES END ----------------#
dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.1
    build_runner: ^2.1.4
    stacked_generator: ^0.7.8

flutter:
    uses-material-design: true
    generate: true

    #-------------------- LOCAL ASSETS ----------------#
    assets:
        - assets/images/
        - assets/sound/correct1.mp3
        - assets/sound/correct2.mp3
        - assets/sound/correct3.mp3
        - assets/sound/error1.mp3
        - assets/sound/error2.mp3
        - assets/sound/error3.mp3

    #-------------------- LOCAL FONTS ----------------#
    fonts:
        - family: troika
          fonts:
              - asset: assets/fonts/troika/troika.otf
